#!/usr/bin/env python3

"""
Application to extract notes from items in Zotero's database.
"""

import sys
import os
import re
import sqlite3

def CleanNote(zkey, note):
    note = re.sub('<div .*?>', '', note, flags=re.M)
    note = re.sub('</div>', '', note, flags=re.M)
    note = re.sub('<em>(.*?)</em>', '*\\1*', note, flags=re.M)
    note = re.sub('<strong>(.*?)</strong>', '**\\1**', note, flags=re.M)
    note = re.sub('<b>(.*?)</b>', '**\\1**', note, flags=re.M)
    note = re.sub('<i>(.*?)</i>', '*\\1*', note, flags=re.M)
    note = re.sub('<br>', '\n', note, flags=re.M)
    note = re.sub('<p>', '', note, flags=re.M)
    note = re.sub('</p>', '\n\n', note, flags=re.M)
    note = re.sub('\(<a href="zotero.*?">(.*?)</a>\)', '[@' + zkey + '#\\1]', note, flags=re.M)
    return note


if __name__ == "__main__":

    if len(sys.argv) < 3:
        sys.stderr.write('Usage:\n\n  ' + sys.argv[0] + ' /path/to/zotero.sqlite zotero_key_1 [zotero_key_2 [zotero_key_3 [...]]]\n')
        sys.exit(1)

    zkeys = []
    for i in range(2, len(sys.argv)):
        zkeys.append(sys.argv[i])

    with open(sys.argv[1], 'rb') as f:
        b = f.read()

    with open("/tmp/zotnote_copy", 'wb') as f:
        f.write(b)

    conn = sqlite3.connect("/tmp/zotnote_copy")
    cur = conn.cursor()

    query = u"""
            SELECT items.itemID, items.key
            FROM items
            """
    cur.execute(query)

    zitems = {}
    for item_id, item_key in cur.fetchall():
        if item_key in zkeys:
            zitems[item_id] = item_key

    cur.execute(u"SELECT itemID FROM deletedItems")
    zdel = []
    for item_id, in cur.fetchall():
        zdel.append(item_id)

    query = u"""
            SELECT itemNotes.itemID, itemNotes.parentItemID, itemNotes.note
            FROM itemNotes
            WHERE
                itemNotes.parentItemID IS NOT NULL;
            """
    cur.execute(query)
    znotes = {}
    for item_id, item_pId, item_note in cur.fetchall():
        if item_pId in zitems and not item_id in zdel:
            if zitems[item_pId] in znotes:
                znotes[zitems[item_pId]] += item_note
            else:
                znotes[zitems[item_pId]] = item_note

    conn.close()
    os.remove("/tmp/zotnote_copy")

    for key in znotes:
        sys.stdout.write(CleanNote(key, znotes[key]))

